services:
  web:
    image: samuelmelianbenito/zendashop:0.0.1
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/zenda
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8443/users/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=zenda
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
